drop schema if exists citemsa_rh;
CREATE SCHEMA IF NOT EXISTS CITEMSA_RH DEFAULT character SET UTF8 COLLATE UTF8_SPANISH2_CI;
USE CITEMSA_RH;
CREATE TABLE PERSONAL(
ID_NOMINA TEXT,
APELLIDO_PATERNO TEXT,
APELLIDO_MATERNO TEXT,
NOMBRE TEXT,
ID_LICENCIA TEXT(7),
VENCIMIENTO_LICENCIA DATE);

INSERT INTO PERSONAL
VALUES ('153','CHAVEZ','MENDEZ','ALFONSO','C557158','2025-08-01');
INSERT INTO PERSONAL
VALUES ('254','REYES','MILAN','LUIS ULISES','C554148','2024-12-05');